// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15/05/2025, 06:52:16
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ollfl/Desktop/devx/DevX2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ollfl/Desktop/devx/DevX2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ollfl/Desktop/devx/DevX2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ollfl/Desktop/devx/DevX2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ollfl/Desktop/devx/DevX2/plugins/**/*.{js,ts,mjs}","C:/Users/ollfl/Desktop/devx/DevX2/composables/**/*.{js,ts,mjs}","C:/Users/ollfl/Desktop/devx/DevX2/utils/**/*.{js,ts,mjs}","C:/Users/ollfl/Desktop/devx/DevX2/pages/faq.vue","C:/Users/ollfl/Desktop/devx/DevX2/pages/about.vue","C:/Users/ollfl/Desktop/devx/DevX2/pages/index.vue","C:/Users/ollfl/Desktop/devx/DevX2/pages/clients.vue","C:/Users/ollfl/Desktop/devx/DevX2/pages/contacts.vue","C:/Users/ollfl/Desktop/devx/DevX2/pages/licenses.vue","C:/Users/ollfl/Desktop/devx/DevX2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ollfl/Desktop/devx/DevX2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ollfl/Desktop/devx/DevX2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;